name: Playwright Tests

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  schedule:
    - cron: "0 3 * * *"  #regression run @ 3 AM, all others run on push or PR to main

jobs:
  smoke-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --grep @smoke

      - if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: smoke-report
          path: playwright-report/
          retention-days: 10    #all reports will be set to a 10 day retention lead to accomodate evaluattion

  api-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --grep @API

      - if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: playwright-report/
          retention-days: 14

  regression-tests:
    if: github.event_name == 'schedule'  #Set only for nightly run, will not run on every push
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --grep @regression

      - if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: playwright-report/
          retention-days: 30